-- create tables
-- type1
CREATE TABLE IF NOT EXISTS '407001' (ID INTEGER ,temperature REAL,density REAL,volume REAL,massflowbegin INTEGER,massflowend INTEGER,mass INTEGER,eventDate TEXT,createdAtDate TEXT, PRIMARY KEY("ID" AUTOINCREMENT))
-- type2
CREATE TABLE IF NOT EXISTS '407004' (ID INTEGER,temperature REAL,density REAL,volume REAL,tankLevel REAL,mass REAL,eventDate TEXT,createdAtdate TEXT, PRIMARY KEY("ID" AUTOINCREMENT))
-- RESPONSE
CREATE TABLE IF NOT EXISTS RESPONSE (ID INTEGER,Request TEXT,Response TEXT,EventDate TEXT,SentDate TEXT,Status TEXT, PRIMARY KEY("ID" AUTOINCREMENT))

-- DOCUMENTS
CREATE TABLE IF NOT EXISTS DOCUMENTS (ID INTEGER,Document TEXT,Response TEXT,EventDate TEXT,SentMessageDate TEXT, CreatedAt TEXT,Status TEXT, PRIMARY KEY("ID" AUTOINCREMENT))